services:
 mongo-patients:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_patient_data:/data/db
    
 mysql-appointment:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_appointment_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-payment:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_payment_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 patient-service:
  depends_on:
    - mongo-patients
  image: r0878914/patient-service
  ports:
    - 8080:8080
  links:
    - mongo-patients
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-patients
   
 payment-service:
  depends_on:
    - mysql-payment
  image: r0878914/payment-service
  ports:
    - 8082:8082
  links:
    - mysql-payment
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-payment
   MYSQL_DB_PORT: 3307

 appointment-service:
  depends_on:
    - mysql-appointment
  image: r0878914/appointment-service
  ports:
    - 8081:8081
  links:
    - mysql-appointment
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-appointment
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - patient-service
     - payment-service
     - appointment-service
   image: r0878914/api-gateway
   ports:
     - 8083:8083
   links:
     - patient-service
     - payment-service
     - appointment-service
   environment:
     PATIENT_SERVICE_BASEURL: patient-service:8080
     PAYMENT_SERVICE_BASEURL: payment-service:8082
     APPOINTMENT_SERVICE_BASEURL: appointment-service:8081

volumes:
 mongodb_patient_data:
 mysql_payment_data:
 mysql_appointment_data: