server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: patient-service-create
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/patients
            - Method=POST
          filters:
            - SetPath=/api/patient
        - id: patient-service-all
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/patients/all
            - Method=GET
          filters:
            - SetPath=/api/patient/all
        - id: patient-service-by-number
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/patients
            - Method=GET
          filters:
            - SetPath=/api/patient
        - id: patient-service-update
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/patients
            - Method=PUT
          filters:
            - SetPath=/api/patient
        - id: patient-service-delete
          uri: http://${PATIENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/patients
            - Method=DELETE
          filters:
            - SetPath=/api/patient
        - id: appointment-service-create
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/appointments
            - Method=POST
          filters:
            - SetPath=/api/appointment
        - id: appointment-service-all
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/appointments
            - Method=GET
          filters:
            - SetPath=/api/appointment
        - id: appointment-service-by-patient-number
          uri: http://${APPOINTMENT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/appointments/patient
            - Method=GET
          filters:
            - SetPath=/api/appointment/patient
        - id: payment-service-create
          uri: http://${PAYMENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/payments
            - Method=POST
          filters:
            - SetPath=/api/payment
        - id: payment-service-all
          uri: http://${PAYMENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/payments/all
            - Method=GET
          filters:
            - SetPath=/api/payment/all
        - id: payment-service-by-appointment-number
          uri: http://${PAYMENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/payments
            - Method=GET
          filters:
            - SetPath=/api/payment
        - id: payment-service-update
          uri: http://${PAYMENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/payments
            - Method=PUT
          filters:
            - SetPath=/api/payment